version: '3.9'

x-app:
  &x-app
  image: app
  build:
    context: .
  env_file:
    - .env
  depends_on:
    db:
      condition: service_healthy

services:

  db:
    image: postgres:13.4
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d $POSTGRES_DB
      interval: 5s
      timeout: 2s
      retries: 3
    ports:
      - 5432:5432

  app:
    <<: *x-app
    ports:
      - 3000:3000
    volumes:
      - ".:/src"
    tty: true
    stdin_open: true

volumes:
  postgres:
