version: '3.9'

x-app:
  &x-app
  image: app
  build:
    context: .
  env_file:
    - .env.local
  environment:
    - POSTGRESQL_HOST=db
    - POSTGRESQL_USER=postgres

services:

  db:
    image: postgres:13.4
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRESQL_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d ${POSTGRES_DB}
      interval: 5s
      timeout: 2s
      retries: 10

  app:
    <<: *x-app
    ports:
      - 3000:3000
    volumes:
      - ".:/src"
    tty: true
    stdin_open: true

volumes:
  postgres:
